name: Update README from JSON

on:
  push:
    paths:
      - 'detailed_projects.json'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate README.md from projects.json
        run: |
          python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'Nitnelav'
          git config --global user.email 'Nitnelav@users.noreply.github.com'
          git add README.md
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update README.md from projects.json [auto]"
          git remote set-url origin https://nitnelav:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${GITHUB_REF_NAME}