name: Update JSON from GitHub

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install requests python-dotenv

      - name: Update detailed_projects.json from github
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          python scripts/update_projects.py

      - name: Commit changes
        run: |
          git config --global user.name 'Nitnelav'
          git config --global user.email 'Nitnelav@users.noreply.github.com'
          git add detailed_projects.json
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update detailed_projects.json from github [auto]"
          git remote set-url origin https://nitnelav:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:${GITHUB_REF_NAME}