name: Update README from JSON

on:
  push:
    paths:
      - 'projects.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate README.md from projects.json
        run: |
          python .github/scripts/generate_readme.py

      - name: Commit changes
        run: |
          git config --global user.name 'Nitnelav'
          git config --global user.email 'Nitnelav@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md from projects.json [auto]"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
